// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Header } from "@/components/layout/Header";
// import { Sidebar } from "@/components/layout/Sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html>
//       <body>
//         <Header />
//         <div className="flex">
//           <Sidebar />
//           <main className="flex-1 ml-64">{children}</main>
//         </div>
//       </body>
//     </html>
//   );
// }

"use client";

import { useState, useEffect } from "react";
import { Header } from "@/components/layout/Header";
import { Sidebar } from "@/components/layout/Sidebar";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isDarkMode, setIsDarkMode] = useState(true);
  const [isConnected, setIsConnected] = useState(false);

  // Load sidebar state from localStorage
  useEffect(() => {
    const savedSidebarState = localStorage.getItem("sidebar-open");
    if (savedSidebarState !== null) {
      setIsSidebarOpen(savedSidebarState === "true");
    }

    const savedTheme = localStorage.getItem("dark-mode");
    if (savedTheme !== null) {
      setIsDarkMode(savedTheme === "true");
    }
  }, []);

  // Save sidebar state
  useEffect(() => {
    localStorage.setItem("sidebar-open", String(isSidebarOpen));
  }, [isSidebarOpen]);

  // Apply theme
  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("dark-mode", String(isDarkMode));
  }, [isDarkMode]);

  const handleSidebarToggle = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  const handleThemeToggle = () => {
    setIsDarkMode(!isDarkMode);
  };

  return (
    <html lang="en" className={isDarkMode ? "dark" : ""}>
      <body className="bg-gray-900 dark:bg-gray-900">
        {/* <Header
          isConnected={isConnected}
          isSidebarOpen={isSidebarOpen}
          onSidebarToggle={handleSidebarToggle}
          onThemeToggle={handleThemeToggle}
          isDarkMode={isDarkMode}
        /> */}
        <div className="flex">
          <Sidebar
            isOpen={isSidebarOpen}
            onToggle={handleSidebarToggle}
            onClose={() => setIsSidebarOpen(false)}
          />
          <main
            className={`flex-1 transition-all duration-300 ${
              isSidebarOpen ? "lg:ml-64" : "lg:ml-20"
            }`}
          >
            <div className="container mx-auto px-4 py-8">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
